#!/bin/bash
# 設定 GitHub Secrets 用於 Docker Hub 認證

echo "========================================="
echo "設定 GitHub Secrets"
echo "========================================="
echo ""
echo "需要設定以下 Secrets:"
echo ""
echo "1. DOCKERHUB_USERNAME"
echo "   - 你的 Docker Hub 用戶名（通常是 morris0518）"
echo ""
echo "2. DOCKERHUB_TOKEN"
echo "   - 匰前往: https://hub.docker.com/settings/security"
echo "   - 點擊 'New Access Token'"
echo "   - 權限選擇: Read, Write, Delete"
echo "   - 複製 Token"
echo ""
echo "========================================="
echo "設定方式："
echo "========================================="
echo ""
echo "方法 1: 使用 gh CLI（推薦）"
echo "----------------------------------------"
echo "gh secret set DOCKERHUB_USERNAME morris0518 --repo cab86r/apple-health-influxdb"
echo "gh secret set DOCKERHUB_TOKEN <your-token> --repo cab86r/apple-health-influxdb"
echo ""
echo "方法 2: 使用 GitHub 硌頁面"
echo "----------------------------------------"
echo "前往: https://github.com/cab86r/apple-health-influxdb/settings/secrets/actions"
echo "點擊 'New repository secret'"
echo "名稱: DOCKERHUB_USERNAME"
echo "值: morris0518"
echo ""
echo "點擊 'New repository secret'"
echo "名稱: DOCKERHUB_TOKEN"
echo "值: <your-docker-hub-token>"
echo ""
echo "========================================="
